# Makefile with dependencies management (Q4)

CXX        = g++
CXXFLAGS   = -Wall  -Wextra -std=c++11
DEPFLAGS   = -MMD
LDFLAGS    =
SRCS       = Date.cpp main.cpp Livre.cpp Auteur.cpp Lecteur.cpp Emprunt.cpp Bibliotheq.cpp
OBJS       = $(SRCS:.cpp=.o)
TARGET     = app
DEPS	   = $(OBJS:.o=.d)

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $(TARGET) $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) $(DEPFLAGS) -c  $<

clean:
	rm -f *.o *.d

mrproper: clean
	rm -f $(TARGET)

exe: $(TARGET)
	./$(TARGET)

-include $(DEPS)
